using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using NUnit.Framework;
using TinyURLPOC.Controllers;
using TinyURLPOC.Data;
using TinyURLPOC.Helpers;
using TinyURLPOC.Parser;

namespace TinyURLPOC.Test.Controller
{
    internal class URLsControllerTests
    {
        private URLsController _urLsController;

        [SetUp]
        public void SetUp()
        {
            _urLsController = new URLsController(new Base64Encoding());
        }

        [Test]
        [Order(1)]
        [TestCase("a2.comasd", "https://tinyurl.com/YTIuY29tYXNk")]
        [TestCase("12a.comasd", "https://tinyurl.com/MTJhLmNvbWFzZA==")]
        [TestCase("    121a.comasd", "https://tinyurl.com/ICAgIDEyMWEuY29tYXNk")]
        [TestCase("http://sometest.comasd", "https://tinyurl.com/aHR0cDovL3NvbWV0ZXN0LmNvbWFzZA==")]
        [TestCase("http:/sometest.comasd", "https://tinyurl.com/aHR0cDovc29tZXRlc3QuY29tYXNk")]
        [TestCase("http:sometest.comasd", "https://tinyurl.com/aHR0cDpzb21ldGVzdC5jb21hc2Q=")]
        [TestCase("http://sometest.comasd", "https://tinyurl.com/aHR0cDovL3NvbWV0ZXN0LmNvbWFzZA==")]
        [TestCase("http:/sometest.comasd", "https://tinyurl.com/aHR0cDovc29tZXRlc3QuY29tYXNk")]
        [TestCase("http:sometest.comasd", "https://tinyurl.com/aHR0cDpzb21ldGVzdC5jb21hc2Q=")]
        public void GetShortUrl_ReturnEncodedBase64ShortUrlForValidInput(string input, string expected)
        {
            Console.WriteLine("Input URL: {0}", input);
            var actual = _urLsController.GetShortUrl(input);
            Console.WriteLine("Short URL: {0}", actual);
            Assert.AreEqual(expected, actual);
        }

        [Test]
        [Order(2)]
        [TestCase("asdf  .com", null)]
        [TestCase("http asdas", null)]
        [TestCase("asdasd as  da", null)]
        [TestCase("http://     sometest.comasd", null)]
        [TestCase("https  :/sometest.comasd", null)]
        [TestCase("http:sometest   .c o m", null)]
        [TestCase("http:sometest   .com    ", null)]
        [TestCase("http:   sometest.com    ", null)]
        [TestCase("", null)]
        public void GetShortUrl_ReturnnullForInValidInput(string input, string expected)
        {
            Console.WriteLine("Input URL: {0}", input);
            var actual = _urLsController.GetShortUrl(input);
            Console.WriteLine("Short URL: {0}", actual);
            Assert.AreEqual(expected, actual);
        }


        [Test]
        [Order(3)]
        [TestCase("asdf.com", "aasd123", "https://tinyurl.com/aasd123")]
        [TestCase("asdfasd.com", "aasd123", "https://tinyurl.com/aasd123")]
        [TestCase("asdf.com", "aasd1234", "https://tinyurl.com/aasd1234")]
        public void GetShortUrlUsingAlias_ReturnShortUrlForValidInputAndAlias(string input, string alias, string expected)
        {
            Console.WriteLine("Input URL: {0}", input);
            Console.WriteLine("Alias: {0}", alias);
            var actual = _urLsController.GetShortUrlUsingAlias(input, alias);

            Console.WriteLine("Short URL: {0}", actual);
            Assert.AreEqual(expected, actual);
        }

        [Test]
        [Order(4)]
        [TestCase("anyRandoUrl.com", "AliasTest1", null)]
        public void GetShortUrlUsingAlias_ReturnNullIfAliasAlreadyExistsInDb(string input, string alias, string expected)
        {
            Console.WriteLine("Input URL: {0}", input);
            Console.WriteLine("Alias: {0}", alias);
            var actual = _urLsController.GetShortUrlUsingAlias(input, alias);

            Console.WriteLine("Short URL: {0}", actual);
            Assert.AreEqual(expected, actual);
        }

        [Test]
        [Order(5)]
        [TestCase("https://tinyurl.com/AliasTest1", "LONGURLtest.com")]
        [TestCase("https://tinyurl.com/AliasTest2", "LONGURLtest.com")]
        public void GetLongUrl_ReturnLongUrl_From_ShortUrlAlias(string input, string expected)
        {
            Console.WriteLine("Input URL: {0}", input);
            var actual = _urLsController.GetLongUrl(input);
            Console.WriteLine("Short URL: {0}", actual);
            Assert.AreEqual(expected, actual);
        }

        [Test]
        [Order(6)]
        [TestCase("https://tinyurl.com/base64generatedURI", "LONGURLtest.com")]
        public void GetLongUrl_ReturnLongUrl_From_ShortUrlAutogeneratedURL(string input, string expected)
        {
            Console.WriteLine("Input URL: {0}", input);
            var actual = _urLsController.GetLongUrl(input);
            Console.WriteLine("Short URL: {0}", actual);
            Assert.AreEqual(expected, actual);
        }




        [Test]
        [Order(7)]
        [TestCase("asdf  .com", null)]
        [TestCase("http asdas", null)]
        [TestCase("asdasd as  da", null)]
        [TestCase("http://     sometest.comasd", null)]
        [TestCase("https  :/sometest.comasd", null)]
        [TestCase("http:sometest   .c o m", null)]
        [TestCase("http:sometest   .com    ", null)]
        [TestCase("http:   sometest.com    ", null)]
        [TestCase("", null)]
        public void GetLongUrl_ReturnNullIfLongUrlDoesNotExist(string input, string expected)
        {
            Console.WriteLine("Input URL: {0}", input);
            var actual = _urLsController.GetLongUrl(input);
            Console.WriteLine("Short URL: {0}", actual);
            Assert.AreEqual(expected, actual);
        }

        [Test]
        [Order(8)]
        [TestCase("LONGURLtest.com", 2)]
        public void GetOriginalUrlCount_ReturntheAmountOfTimesTheURLisRetrieved(string input, int expected)
        {
            // calling the long URL 
            var firstCall = _urLsController.GetLongUrl("https://tinyurl.com/AliasTest1");
            var secondCall = _urLsController.GetLongUrl("https://tinyurl.com/AliasTest2");

            var actual = _urLsController.GetOriginalUrlCount(input);
            Assert.AreEqual(expected, actual);

            var thirdCall = _urLsController.GetLongUrl("https://tinyurl.com/base64generatedURI");
            var newActual = _urLsController.GetOriginalUrlCount(input);
            Assert.AreNotEqual(expected, newActual);
        }

        [Test]
        [Order(9)]
        [TestCase("https://tinyurl.com/AliasTest1", 0)]
        [TestCase("https://tinyurl.com/base64generatedURI", 0)]
        public void DeleteLongUrl_ReturnTrueIfTheSelectedRecordToDeleteExists(string input, int expected)
        {
            int currentCount = _urLsController.GetOriginalUrlCount("LONGURLtest.com");
            Console.WriteLine("current count: {0}", currentCount);

            _urLsController.DeleteLongUrl(input);

            int newCount = _urLsController.GetOriginalUrlCount("LONGURLtest.com");
            Console.WriteLine("new count after deleting record: {0}", newCount);

            Assert.AreEqual(expected, newCount);
        }

        [Test]
        [Order(10)]
        [TestCase("https://tinyurl.com/AliasTest1asd", 0)]
        [TestCase("https://tinyurl.com/base64generatedURIasda", 0)]
        public void DeleteLongUrl_ReturnFalseIfTheSelectedRecordToDeleteDOESNOTExists(string input, int expected)
        {
            int currentCount = _urLsController.GetOriginalUrlCount("LONGURLtest.com");
            Console.WriteLine("current count: {0}", currentCount);

            _urLsController.DeleteLongUrl(input);

            int newCount = _urLsController.GetOriginalUrlCount("LONGURLtest.com");
            Console.WriteLine("new count after deleting record: {0}", newCount);

            Assert.AreEqual(expected, newCount);
        }
    }
}
