using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TinyURLPOC.Models
{
    public class UrlMapping
    {
        public int Id { get; set; }
        public string OriginalUrl { get; set; }
        //Auto generated URL - the hash is also unique 
        public string AutoGeneratedUrl { get; set; }
        //Increase count everytime the original URL is retrieved from the auto generated URL or the alias 
        public int ShortenedUrlCount { get; set; } = 0;
        public List<Alias> Alias { get; set; } = new List<Alias>();

    }
}
