using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using TinyURLPOC.Data;
using TinyURLPOC.Models;

namespace TinyURLPOC.Helpers
{
    public class DataBaseHelper
    {
        public Dictionary<string, UrlMapping> URLMappings { get; set; }
        public Dictionary<string, string> Aliases { get; set; }

        public DataBaseHelper()
        {
            //K - original URL 
            //V - UrlMapping Model
            URLMappings = new Dictionary<string, UrlMapping>();


            //K - unique alias 
            //V - original URL 
            Aliases = new Dictionary<string, string>();

            #region DEBUG Populating Dummy Values

            var testAlias1 = new Alias()
            {
                Name = "AliasTest1",
                //EncodedName = "https://tinyurl.com/AliasTest1"
            };
            var testAlias2 = new Alias()
            {
                Name = "AliasTest2",
                //EncodedName = "https://tinyurl.com/AliasTest2"
            };
            var testUrlMapping = new UrlMapping()
            {
                OriginalUrl = "LONGURLtest.com",
                AutoGeneratedUrl = "base64generatedURI",
                Alias = new List<Alias>()
                {
                    testAlias1, testAlias2
                }
            };
            
            URLMappings.Add(testUrlMapping.OriginalUrl, testUrlMapping);
            Aliases.Add(testAlias1.Name, testUrlMapping.OriginalUrl);
            Aliases.Add(testAlias2.Name, testUrlMapping.OriginalUrl);

            #endregion

        }

    }
}
